// Display modes
export const DISPLAY_TEMPERATURE_DATA = "DISPLAY_TEMPERATURE_DATA";
export const DISPLAY_LIGHT_CONTROLS = "DISPLAY_LIGHT_CONTROLS";
export const DISPLAY_ATMOSPHERE_DATA = "DISPLAY_ATMOSPHERE_DATA";
export const DISPLAY_FAUNA_FLORA = "DISPLAY_FAUNA_FLORA";
export const DISPLAY_LIVE_FEED = "DISPLAY_LIVE_FEED";